apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: auth
      port: 9302
      targetPort: 9302
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: yangyuw/auth:1.0
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 9302
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9302
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9302
          env:
            - name: TZ
              value: "Asia/Shanghai"
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "512Mi"