apiVersion: v1
kind: Service
metadata:
  name: code
spec:
  selector:
    app: code
  ports:
    - name: code
      port: 9502
      targetPort: 9502
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code
  labels:
    app: code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      labels:
        app: code
    spec:
      containers:
        - name: code
          image: yangyuw/code:1.0
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 9502
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9502
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9502
          env:
            - name: TZ
              value: "Asia/Shanghai"
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "512Mi"