apiVersion: v1
kind: Service
metadata:
  name: fronted
spec:
  type: NodePort
  selector:
    app: fronted
  ports:
    - name: fronted
      port: 3306
      targetPort: 3306
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted
  labels:
    app: fronted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fronted
  template:
    metadata:
      labels:
        app: fronted
    spec:
      containers:
        - name: fronted
          image: fronted:1.0
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 6379
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 6379
          env:
            - name: TZ
              value: "Asia/Shanghai"
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "512Mi"