apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: gateway
      port: 9201
      targetPort: 9201
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: yangyuw/gateway:1.0
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 9201
              protocol: TCP
          # livenessProbe:
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   tcpSocket:
          #     port: 9201
          # readinessProbe:
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   tcpSocket:
          #     port: 9201
          env:
            - name: TZ
              value: "Asia/Shanghai"
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "512Mi"