apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysql-mysql
      port: 3306
      targetPort: 3306
      appProtocol: mysql
      protocol: TCP