apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-vol
          hostPath:
            path: /data/redis
            type: DirectoryOrCreate
      containers:
        - name: redis
          image: redis:6.0.9-alpine
          command:
            - redis-server 
            - --appendonly 
            - yes  
            - --requirepass 
            - "f5DD56xIRboWqTK"
          imagePullPolicy: Always
          volumeMounts:
            - name: redis-vol
              subPath: redis-vol
              mountPath: /data
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 6379
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 6379
          env:
            - name: TZ
              value: "Asia/Shanghai"
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "512Mi"