apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: phoenix-dev
spec:
  selector:
    app: redis
  ports:
    - name: redis-redis
      port: 6379
      targetPort: 6379
      appProtocol: redis
      protocol: TCP